<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function umichoidc_ctools_plugin_directory($module, $plugin) {
  if ($module == 'openid_connect') {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_user_presave().
 */
function umichoidc_user_presave(&$edit, $account, $category) {

  // Make sure that our form value 'mymodule_foo' is stored as
  // 'mymodule_bar' in the 'data' (serialized) column.
  if (isset($edit['mymodule_foo'])) {
    $edit['data']['mymodule_bar'] = $edit['mymodule_foo'];
  }
}
